pipelines:
  - pl_name: "del_changyi_inboundcdp_to_startdt_outboundcdp"
    schedule: "* * * * *"
    source:
      path: "C:\\scheduler\\temp\\source"
    target:
      path: "C:\\scheduler\\temp\\target"
    operation: "move"  # 指定操作类型，可以是 "move" 或 "copy"
    sns_topic: "datalab-cn-airflowsns-newcdp"